app:
    resource: "@AppBundle/Controller/"
    type:     annotation

symfonian_indonesia:
    resource: .
    type: siab

symfonian_indonesia_index:
    resource: @SymfonianIndonesiaAdminBundle/Controller
    type: annotation

symfonian_indonesia_security:
    resource: @SymfonianIndonesiaAdminBundle/Security
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile